TITLE = 'Guessing Game'

FONT = 'Ink Free'

WINDOW_SIZE = 300
RESIZABLE = False
WINDOW_COLOR = '#684484'

CREAMY = '#fff897'

BUTTON_TEXT_COLOR = WINDOW_COLOR
BUTTON_HOVER_COLOR = '#fdff3d'

LARGE_FONT_SIZE = 30
MEDIUM_FONT_SIZE = 20
SMALL_FONT_SIZE = 15

CORNER_RADIUS = 10

WRONG_GUESS_COLOR = '#ff2020'
RIGHT_GUESS_COLOR = '#14c5af'

MAX_NUMBER = 10_000
LOW_ANSWER = 'LOW'
HIGH_ANSWER = 'HIGH'
EXACT_ANSWER = 'EXACT'
