TITLE = 'Guessing Game'

FONT = 'Candara'

WINDOW_SIZE = 300
RESIZABLE = False
WINDOW_COLOR = '#04184f'

CREAMY = '#f8ffe5'

BUTTON_TEXT_COLOR = WINDOW_COLOR
BUTTON_HOVER_COLOR = '#d8dde5'

LARGE_FONT_SIZE = 30
MEDIUM_FONT_SIZE = 20
SMALL_FONT_SIZE = 15

CORNER_RADIUS = 10

WRONG_GUESS_COLOR = '#ef476f'
RIGHT_GUESS_COLOR = '#06d6a0'

MAX_NUMBER = 10_000
LOW_ANSWER = 'LOW'
HIGH_ANSWER = 'HIGH'
EXACT_ANSWER = 'EXACT'
